### ISSUE TITLE
Tests for class Client using metatests

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/impress#1021]
This class becoming stable and it's time to create tests for it using metatests

**Comment by mille-nium** [comment]
@tshemsedinov I wonder, why here https://github.com/metarhia/impress/blob/39671bdb6d09693f509eb5797f6b73d8ed54590a/lib/client.js#L613-L620 we check if `cache` is type of `number`, because AFAIS we always add to this Map( in `client` as well as in `application` interface) only objects, like here, for example https://github.com/metarhia/impress/blob/39671bdb6d09693f509eb5797f6b73d8ed54590a/lib/client.js#L674-L676
So, if I'm not mistaken, `cache` can be only type of `object` or `undefined`
