### ISSUE TITLE
Support for custom `context` provider

### ISSUE THREAD

**Issue by nechaido** [metarhia/impress#1811]
### Describe the problem

The need to have additional context parameters such as:
* BuisnessProcessID
* `BuisnessProcessID`- bound logger
* database connection that is already in transaction mode

### Describe the solution

I'd like the ability to provide a custom function and/or class that would be responsible for adding additional properties to the `context` object.

### Alternatives

This could be done manually but often results in boilerplate code.

### Additional context

See https://github.com/metatech-university/NodeJS-Application/pull/4/files#diff-76374afb32b513f9f1f3ad04638ffcfba3c4cd36aa447236a128c2b6ed6c0936R4

**Comment by tshemsedinov** [comment]
Now we have: 
* per connection `context` and `context.uuid` autogenerated to identify connection context
* persistently stored `context.session` for whole session identified by `context.session.token`
* and `context.session.accountId` to identify certain user

See example: https://github.com/metarhia/Example/blob/34e4bb05b3048778c28dff675cfe64f9159b87d9/application/api/example.1/getClientInfo.js#L1-L9

I think we do not need session or connection bounded logger, because we use local logs for system logging, while for business-process logging we need separate place: `Journal` (system wide, single for all servers)

Also I do not think that we need database connection in context associated with certain transaction, we can do it in different way: any transaction should be started/committed/rolledback in a single routine, if we need to pass a reference to a connection to other procedures, we can do it manually, but I'd like to have start/commit/rollback in one place and use passed reference just for queries but not for doing operations with transaction.

**Comment by tshemsedinov** [comment]
Also we do not need class or factory function for context, what we need is a schema and .d.ts typing

**Comment by tshemsedinov** [comment]
Platform should catch all context identifiers like `context.uuid` when we
- `throw`
- `return Error`
- `console.*`
and write to logs

Alternatively we can register ids manually:
- by `context.tag: object`
- or `context.registerLogId('key', value)` or `console.registerLogId('key', value)`

**Comment by tshemsedinov** [comment]
Partially done in Version 3.0.0, other features requires consensus and we will open new issues for them
