### ISSUE TITLE
Add generator functions support

### ISSUE THREAD

**Issue by bolein** [metarhia/Impress#526]
It would be great to have a possibility to declare handlers as ES6 generator functions.

**Comment by tshemsedinov** [comment]
Current Impress version `0.1.*` supports even Node.js 0.10 and 0.11, last one supports generators but with special CLI parameter `--harmony-generators`. We will support it in version `0.3.*`, see #527 for details. You may prepare an example of such handler here and use cases.

**Comment by bolein** [comment]
@tshemsedinov thanks for reply :+1: 
here's simple use case:

```JS
'use strict';

module.exports = function*(client, callback) {

    let userId = client.query.userId;

    let response = yield {
        user: userService.getUser(userId),
        count: messageService.getUnreadConversationsCount(userId),
        conversations: messageService.getConversations(userId, client.query.offset, client.query.limit)
    };

    callback(JSON.stringify(response), 200);
};
```

I guess the whole deal is only to implement executor function that will wrap handlers declared as generator functions. I guess I could do it by myself, but I'm not yet familiar with the project and can't find the place where handler execution takes place :) any hint?

**Comment by tshemsedinov** [comment]
@bolein how do you think mentioned fragment should work? If you expect than it will wait for 3 functions execution: `userService.getUser`, `messageService.getUnreadConversationsCount` and `messageService.getConversations` it can't do that because those functions have no callbacks and have no other methods to report when they will finish. Generator functions are used for other purpose, so I am planning to implement remote generators, calling them from client-side you will have js generator and can use it in `for(let code of generator) {...}`, use `generator.next(...)` and other generators bechaviour. @aqrln may have additional comments

**Comment by bolein** [comment]
True. Those functions don't have callbacks. Because in my example generators are used to fight the callbacks. Those functions are whether the generators themselves or they return promises etc. You should probably check out how generators are used [this way](http://jlongster.com/A-Study-on-Solving-Callbacks-with-JavaScript-Generators) and also the [co](https://github.com/tj/co) library as an example of what I'm talking about here

**Comment by tshemsedinov** [comment]
Ok, @aqrln please, research how can we use such an approach.
