### ISSUE TITLE
Make server events work again

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/Impress#628]
After multiple changes in server core distributed events are not working.

**Comment by aqrln** [comment]
Make server events great again

**Comment by tshemsedinov** [comment]
In `/lib/impress.cloud.js` in function `setupEventHandlers` we receive event from JSTP, but following expected fields of `event` are undefined: `packetId`, `interfaceName`, `remoteEventName`, `remoteEventArgs`. Also do we need `event.connection` and `event.application` ?

See: https://github.com/metarhia/Impress/blob/master/lib/impress.cloud.js#L212
Example:
```js
// event:
{
  packetType: 'event',
  packet: {
    event: {
      from: 'S1N3',
      app: 'example',
      name: 'test',
      target: 'backend',
      data: [Object]
    }
  },
  packetId: undefined,
  interfaceName: undefined,
  remoteEventName: undefined,
  remoteEventArgs: undefined,
  connection: .....,
  application: .....
}
```

**Comment by aqrln** [comment]
@tshemsedinov this behavior has been caused by the duplicate keys in JSTP packets (`event` for the packet kind and `event` for the event name). After fixing this by renaming the event to `impressEvent`, server events still don't work since `impress.applications`, used by `impress.api.cloud.event` is an empty hash for some reason, so application lookup fails at https://github.com/metarhia/Impress/blob/master/lib/impress.cloud.js#L236
