### ISSUE TITLE
Optimise logger's file buffer

### ISSUE THREAD

**Issue by primeare** [metarhia/impress#702]
It's better to use array rather than string for file buffer in [impress.log.js](../blob/master/lib/impress.log.js#L123)

**Comment by aqrln** [comment]
@primeare and write this array of strings at once in corked mode in `application.log.flush` (so that a single `writev` syscall instead of multiple `write`s is used), right. That will be much more performant. If you'd like to open a PR, go for it.

**Comment by aqrln** [comment]
But keep in mind that the only possible optimization here is purely IO-specific. I don't know what you meant when you was opening this issue since you didn't provide any rationale or description, so if you thought of using an array instead of sequential string concatenation so that it can be joined later (like it is commonly done in Python), it would not work :) String concatenation is very fast and efficient in JavaScript because it uses splay trees internally, even faster than joining an array of strings, contrary to other programming languages. So the key point is that there's no need for concatenation at all, let the kernel write a vector of buffers sequentially as one operation. You can ping me if you'll have questions about `cork` and `writev` or you'll need any help.

**Comment by tshemsedinov** [comment]
Further development here: https://github.com/metarhia/metalog
