### ISSUE TITLE
/bin/sh: 1: kill: No such process

### ISSUE THREAD

**Issue by dmitrystas** [metarhia/impress#741]
Sometimes when i try to stop Impress from the command line I get something like this:

> root@debian:/ias# impress stop
> Impress Application Server 0.4.20
> 
> Error: Command failed: kill 11669
> /bin/sh: 1: kill: No such process
> 
> Error: Command failed: kill 11674
> /bin/sh: 1: kill: No such process
> 
> Error: Command failed: kill 11676
> /bin/sh: 1: kill: No such process
> 
> Stopped

But not always, only sometimes. Bug? Or what`s wrong?

**Comment by belochub** [comment]
It is not really an issue of `impress` itself, it is an issue of `impress-cli`.

It happens due to the following race condition:
Whenever you do `impress start`, it launches `impress` starting with the master instance (Cloud Controller) and afterwards this process starts other workers by forking, thus creating child processes dependent on the master process. On `impress stop` `impress-cli` finds all of the processes of `impress` in the system (both master and worker processes) and starts killing them one by one starting with master. Killing master process triggers operating system to also kill its child processes (`impress` workers), thus leading to the situation where both `impress-cli` and operating system are killing the same processes at the same time, and whenever the operating system manages to kill some of the workers before `impress` does, the message you mentioned will be printed to `stdout`.

This issue should be moved to [`impress-cli`](https://github.com/metarhia/impress-cli) repository.

**Comment by tshemsedinov** [comment]
@belochub `impress-cli` is a part of impress so I'd prefer to use this issue list, even listed this list as a bug tracker for `impress-cli` package [here](https://github.com/metarhia/impress-cli/blob/master/package.json#L18).

@aqrln and @belochub can you guys fix it please?
