### ISSUE TITLE
Refactor loop variables

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/impress#864]
Remove external variable declarations and move variables inside loop statements, for example: https://github.com/metarhia/metasync/pull/370
New comparison tests shows that external declaration gives no performance advantages anymore.

**Comment by JuliaGerasymenko** [comment]
One question, please. 
  If we have conditional statements inside the loop e. g. https://github.com/metarhia/impress/blob/master/lib/api.test.js#L78 
if (result instanceof RegExp) {
        sResult = result.toString() + '';
        sResult = '"' + sResult.substring(1, sResult.length - 1) + '"';
      } else if (result instanceof Buffer) {
        sResult = result.toString();
      } else {
        sResult = api.json.stringify(result);
      }  

We can do like this.

if (result instanceof RegExp) {
        let sResult = result.toString() + '';
        sResult = '"' + sResult.substring(1, sResult.length - 1) + '"';
      } else if (result instanceof Buffer) {
        const sResult = result.toString();
      } else {
        const sResult = api.json.stringify(result);
      }

  Or  take out on L77 before the condition statement                    let sResult;            ?

**Comment by tshemsedinov** [comment]
We definitely should not mix `let` and `const` for the same identifier, so better put `let sResult;` before conditional statement. @JuliaGerasymenko

**Comment by nechaido** [comment]
@tshemsedinov looks like `api.test` duplicates the functionality of `metatests` should we, maybe, use `metatests` instead of refactoring?

**Comment by tshemsedinov** [comment]
@nechaido agree to remove

**Comment by lundibundi** [comment]
Also, @JuliaGerasymenko in your change you have changed the actual meaning of the code. Before there was a variable `sResult` that has been assigned some value after this if-else-statement has been executed. After your change the values (sResult) will be limited to the specific branch and will not exist outside of them which may be (and here it is incorrect as this is the same code as in metatests/lib/case.js) incorrect. The change @tshemsedinov suggested with `let` before the branch on the other hand would have been fine as it preserves the logic (though variable may not live long enough because the may be some other scope. but that's not visible in this example).
